CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306105311_SyncUsersRolesSchema') THEN

    CREATE TABLE IF NOT EXISTS roles (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        role_name TEXT
    );

    ALTER TABLE roles ADD COLUMN IF NOT EXISTS role_name TEXT;

    INSERT INTO roles(id, role_name) VALUES
        (1, 'user'),
        (2, 'admin_divisi'),
        (3, 'super_admin'),
        (4, 'super_duper_admin')
    ON CONFLICT (id) DO UPDATE SET role_name = EXCLUDED.role_name;

    CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        full_name TEXT,
        email TEXT,
        password_hash TEXT,
        role_id INTEGER NOT NULL DEFAULT 1,
        position TEXT,
        company_id INTEGER,
        department_id INTEGER,
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMPTZ,
        mfa_secret TEXT,
        mfa_enabled BOOLEAN,
        high_value_threshold NUMERIC
    );

    ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS email TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS role_id INTEGER;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS position TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS company_id INTEGER;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS department_id INTEGER;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_secret TEXT;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_enabled BOOLEAN;
    ALTER TABLE users ADD COLUMN IF NOT EXISTS high_value_threshold NUMERIC;

    UPDATE users SET role_id = 1 WHERE role_id IS NULL;
    UPDATE users SET is_active = TRUE WHERE is_active IS NULL;

    ALTER TABLE users ALTER COLUMN role_id SET DEFAULT 1;
    ALTER TABLE users ALTER COLUMN is_active SET DEFAULT TRUE;

    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'fk_users_roles_role_id'
        ) THEN
            ALTER TABLE users
                ADD CONSTRAINT fk_users_roles_role_id
                FOREIGN KEY (role_id)
                REFERENCES roles(id)
                ON DELETE RESTRICT;
        END IF;
    END $$;

    CREATE TABLE IF NOT EXISTS daily_report (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        report_date DATE NOT NULL,
        report_time TIME WITHOUT TIME ZONE NOT NULL,
        task_description TEXT,
        issue TEXT,
        solution TEXT,
        result TEXT,
        status TEXT,
        manager_note TEXT,
        attachment_path TEXT,
        department_id INTEGER,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'fk_daily_report_users_user_id'
        ) THEN
            ALTER TABLE daily_report
                ADD CONSTRAINT fk_daily_report_users_user_id
                FOREIGN KEY (user_id)
                REFERENCES users(id)
                ON DELETE CASCADE;
        END IF;
    END $$;

    CREATE TABLE IF NOT EXISTS daily_report_attachments (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        report_id INTEGER NOT NULL,
        attachment_path TEXT,
        file_type TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );

    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'fk_daily_report_attachments_daily_report_report_id'
        ) THEN
            ALTER TABLE daily_report_attachments
                ADD CONSTRAINT fk_daily_report_attachments_daily_report_report_id
                FOREIGN KEY (report_id)
                REFERENCES daily_report(id)
                ON DELETE CASCADE;
        END IF;
    END $$;

    CREATE INDEX IF NOT EXISTS ix_daily_report_user_id ON daily_report (user_id);
    CREATE INDEX IF NOT EXISTS ix_daily_report_attachments_report_id ON daily_report_attachments (report_id);
    CREATE INDEX IF NOT EXISTS ix_users_role_id ON users (role_id);

    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260306105311_SyncUsersRolesSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260306105311_SyncUsersRolesSchema', '8.0.0');
    END IF;
END $EF$;
COMMIT;

